name: formz
description: A unified form representation in Dart which aims to simplify form representation and validation in a generic way.
repository: https://github.com/ChicagoFlutter/formz
issue_tracker: https://github.com/ChicagoFlutter/formz/issues
homepage: https://github.com/ChicagoFlutter/formz
documentation: https://github.com/ChicagoFlutter/formz

version: 0.4.0-nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.9
  test_coverage: ^0.5.0
